### ISSUE TITLE
Might be better to replace stability with Gradient-Richardson-No

### ISSUE THREAD

**Issue by jonasViehweger** [jonasViehweger/energyBudget#20]
https://github.com/jonasViehweger/fieldClim/blob/8e087a48cb975e3a44fa3ba4bc1c0d42ec55e52d/R/turbulent_flux.R#L19

Wenn man die Gradient-Richardson-No direkt eingibt, müsste nicht der Umweg über die Konvertierung zu strings gegangen werden.

**Comment by langdav** [comment]
Find ich gut, würde die Stabilität aber dennoch berechnen und mit in den Ausgabe-Dataframe packen (als Information)
