### ISSUE TITLE
It should be possible to give a single value to albedo

### ISSUE THREAD

**Issue by jonasViehweger** [jonasViehweger/energyBudget#25]
https://github.com/jonasViehweger/fieldClim/blob/c5c291abee96464e4a46c4a359683a35521d5e23/R/weather_station.R#L77

Right now later the constructor would abort since albedo would be too short. That's an issue if albedo isn't measured continuously.

**Comment by langdav** [comment]
wenn nur ein Albedo angegeben ist, diesen einfach lenght(datetime)-mal pasten?
wenn mehrere Werte angegeben sind, diese aber in geringerer Frequenz als die restlichen Messwerte aufgenommen wurden, diese in die "Zwischenzeiten" pasten?

**Comment by jonasViehweger** [comment]
Done in 6b3f17540a5f4d59d98ef7df9417f0bfcab3b868
